services:
  db:
    image: postgis/postgis:16-3.5
    ports:
      - "5435:5432" 
    environment:
      - POSTGRES_DB=odoo16
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo16
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo16-db-data:/var/lib/postgresql/data

  odoo_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo16
      - DB_PASSWORD=odoo
      - DB_NAME=odoo16
    volumes:
      - ./extra-addons/geospatial:/mnt/extra-addons/geospatial
      - ./extra-addons/timesheet:/mnt/extra-addons/timesheet
      - ./extra-addons/field-service:/mnt/extra-addons/field-service
      - ./extra-addons/avanzosc:/mnt/extra-addons/avanzosc
      - ./extra-addons/web:/mnt/extra-addons/web
      - ./extra-addons/partner-contact:/mnt/extra-addons/partner-contact
      - ./jbm_addons:/mnt/jbm_addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo16-web-data:/var/lib/odoo
    command: odoo -u project_map
    # command: odoo -u base,\
    #           base_geoengine,base_geoengine_demo,base_geolocalize,base_geolocalize_company,\
    #           timesheet,field_service,avanzosc,web,partner_contact,project_map

volumes:
  odoo16-web-data:
  odoo16-db-data:
  